#!/bin/bash
#SBATCH -J make_patches
#SBATCH -C genoa
#SBATCH -p cmbas
#SBATCH -t 20:00:00
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=8
#SBATCH --cpus-per-task=8
#SBATCH --mem=600G
#SBATCH -o /mnt/ceph/users/abayer/joboutput/make_patches.o%j
#SBATCH --mail-user=abayer@berkeley.edu
#SBATCH --mail-type=all

module load modules/2.2
module load python/3.10.10
module load openmpi python-mpi
source $VENVDIR/pyrecon/bin/activate
cd /mnt/home/abayer/source/ddprism/ddprism/tsz_cmb

outBASE="/mnt/home/abayer/ceph/fastpm/halfdome/oneweek/final"

for profile_str in 'b16' 'b16g7' 'b16g7rel'; do

outdir="${outBASE}/${profile_str}/patches/"
mkdir -p "$outdir"

# python make_patches.py --profile_str=$profile_str --dataset_name=T_tot --noise=7.0 --outdir="$outdir"
# python make_patches.py --profile_str=$profile_str --dataset_name=dT_tsz --noise=0.0 --outdir="$outdir"
# python make_patches.py --profile_str=$profile_str --dataset_name=T_tot --random_pos --noise=7.0 --outdir="$outdir"
# python make_patches.py --profile_str=$profile_str --dataset_name=dT_tsz --random_pos --noise=0.0 --outdir="$outdir"
python make_patches.py --profile_str=$profile_str --dataset_name=T_tot --random_pos --noise=0.0 --outdir="$outdir"

done
